import os

part2 = (
    "    # ==================== 截图工具 ====================\n"
    "\n"
    "    def _take_screenshot(self, save_path='current_screen.png'):\n"
    "        try:\n"
    "            self._d.screenshot(save_path)\n"
    "            return cv2.imread(save_path)\n"
    "        except Exception as e:\n"
    "            logger.error(f'[PhysicalTool] 截图失败: {e}')\n"
    "            return None\n"
    "\n"
    "    def _img_hash(self, img):\n"
    "        return hashlib.md5(img.tobytes()).hexdigest()\n"
    "\n"
    "    # ==================== OCR 兜底 ====================\n"
    "\n"
    "    def _detect_via_ocr(self, save_path='current_screen.png'):\n"
    "        if not self.ready:\n"
    "            return None\n"
    "        img = self._take_screenshot(save_path)\n"
    "        if img is None:\n"
    "            return None\n"
    "        h, w = img.shape[:2]\n"
    "        chat = img[int(h*0.10):int(h*0.88), 0:int(w*0.60)]\n"
    "        cur_hash = self._img_hash(chat)\n"
    "        if cur_hash == self._last_hash:\n"
    "            return None\n"
    "        prev = self._last_frame\n"
    "        self._last_frame = chat.copy()\n"
    "        self._last_hash  = cur_hash\n"
    "        if prev is None or prev.shape != chat.shape:\n"
    "            return None\n"
    "        diff      = cv2.absdiff(prev, chat)\n"
    "        diff_mean = float(diff.mean())\n"
    "        if diff_mean < FRAME_DIFF_THRESHOLD:\n"
    "            return None\n"
    "        logger.debug(f'[OCR兜底] 帧差={diff_mean:.2f}')\n"
    "        ch, cw = chat.shape[:2]\n"
    "        diff_gray = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)\n"
    "        _, diff_bin = cv2.threshold(diff_gray, 20, 255, cv2.THRESH_BINARY)\n"
    "        kernel   = cv2.getStructuringElement(cv2.MORPH_RECT, (20, 10))\n"
    "        diff_bin = cv2.dilate(diff_bin, kernel)\n"
    "        contours, _ = cv2.findContours(diff_bin, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)\n"
    "        if not contours:\n"
    "            return None\n"
    "        rx, ry, rw, rh = cv2.boundingRect(max(contours, key=cv2.contourArea))\n"
    "        pad    = 20\n"
    "        region = chat[max(0,ry-pad):min(ch,ry+rh+pad), max(0,rx-pad):min(cw,rx+rw+pad)]\n"
    "        wp = float(cv2.inRange(region, BUBBLE_WHITE_LOW, BUBBLE_WHITE_HIGH).sum())\n"
    "        gp = float(cv2.inRange(region, BUBBLE_GREEN_LOW, BUBBLE_GREEN_HIGH).sum())\n"
    "        if gp > wp * 1.5 and gp > 0.005 * region.size:\n"
    "            logger.debug('[OCR兜底] 绿色气泡，跳过')\n"
    "            return None\n"
    "        try:\n"
    "            results = self._ocr.readtext(region)\n"
    "        except Exception as e:\n"
    "            logger.error(f'[OCR兜底] 识别失败: {e}')\n"
    "            return None\n"
    "        if not results:\n"
    "            return None\n"
    "        for bbox, text, prob in sorted(results, key=lambda r: r[0][2][1], reverse=True):\n"
    "            t = text.strip()\n"
    "            if not t or len(t) < 3 or prob < 0.5:\n"
    "                continue\n"
    "            if _RE_NOISE.match(t) or _RE_NUMONLY.match(t):\n"
    "                continue\n"
    "            if t.lower() in _SYS_NOISE:\n"
    "                continue\n"
    "            logger.info(f\"[PhysicalTool] \u2705 顾客新消息(OCR): '{t[:40]}'\")\n"
    "            return t\n"
    "        return None\n"
    "\n"
    "    # ==================== 统一入口 ====================\n"
    "\n"
    "    def detect_new_customer_message(self, save_path='current_screen.png', chat_crop=None):\n"
    "        msg = self._read_via_ui()\n"
    "        if msg:\n"
    "            return msg\n"
    "        return self._detect_via_ocr(save_path)\n"
    "\n"
    "    # ==================== 兼容旧接口 ====================\n"
    "\n"
    "    def screenshot_and_ocr(self, save_path='current_screen.png', crop=(0.0, 0.15, 1.0, 0.88)):\n"
    "        if not self.ready:\n"
    "            return []\n"
    "        try:\n"
    "            img = self._take_screenshot(save_path)\n"
    "            if img is None:\n"
    "                return []\n"
    "            h, w = img.shape[:2]\n"
    "            l, t, r, b = crop\n"
    "            return self._ocr.readtext(img[int(h*t):int(h*b), int(w*l):int(w*r)])\n"
    "        except Exception as e:\n"
    "            logger.error(f'[PhysicalTool] OCR失败: {e}')\n"
    "            return []\n"
    "\n"
    "    def extract_latest_message(self, results):\n"
    "        if not results:\n"
    "            return None\n"
    "        for bbox, text, prob in sorted(results, key=lambda r: r[0][2][1], reverse=True):\n"
    "            t = text.strip()\n"
    "            if not t or len(t) < 2 or prob < 0.5:\n"
    "                continue\n"
    "            try:\n"
    "                sw = self._d.window_size()[0] if self._d else 1080\n"
    "            except Exception:\n"
    "                sw = 1080\n"
    "            if (bbox[0][0] + bbox[2][0]) / 2 > sw * 0.65:\n"
    "                continue\n"
    "            return t\n"
    "        return None\n"
    "\n"
    "    # ==================== 发送操作 ====================\n"
    "\n"
    "    def send_message(self, input_x, input_y, text):\n"
    "        if not self._d:\n"
    "            return False\n"
    "        try:\n"
    "            self._d.click(input_x, input_y)\n"
    "            time.sleep(0.2)\n"
    "            self._d.send_keys(text)\n"
    "            time.sleep(0.1)\n"
    "            self._d.press('enter')\n"
    "            logger.info(f'[PhysicalTool] 消息已发送: {text[:30]}')\n"
    "            return True\n"
    "        except Exception as e:\n"
    "            logger.error(f'[PhysicalTool] 发送消息失败: {e}')\n"
    "            return False\n"
    "\n"
    "    def send_payment_qr(self, input_x, input_y, price):\n"
    "        if not self._d:\n"
    "            return False\n"
    "        if not os.path.exists(self.qr_path):\n"
    "            return self.send_message(input_x, input_y, f'兄弟，请扫收款码，总计 {price:.0f} 元！')\n"
    "        try:\n"
    "            self._d.push(self.qr_path, '/sdcard/Pictures/payment_qr.png')\n"
    "            time.sleep(0.5)\n"
    "            more = self._d.xpath('//*[@content-desc=\"更多\"] | //*[@resource-id=\"com.tencent.mm:id/bfp\"]')\n"
    "            if more.exists:\n"
    "                more.click()\n"
    "            else:\n"
    "                self._d.click(input_x + 130, input_y)\n"
    "            time.sleep(0.8)\n"
    "            album = self._d.xpath('//*[@content-desc=\"相册\"]')\n"
    "            if not album.exists:\n"
    "                raise RuntimeError('相册按钮未找到')\n"
    "            album.click()\n"
    "            time.sleep(1.2)\n"
    "            thumb = self._d.xpath('//*[@resource-id=\"com.tencent.mm:id/h1y\"] | //*[@resource-id=\"com.tencent.mm:id/thumbnail\"]')\n"
    "            if thumb.exists:\n"
    "                thumb.click()\n"
    "            else:\n"
    "                sz = self._d.window_size()\n"
    "                self._d.click(int(sz[0]*0.15), int(sz[1]*0.25))\n"
    "            time.sleep(0.5)\n"
    "            send_btn = self._d.xpath('//*[@content-desc=\"发送\"] | //*[@resource-id=\"com.tencent.mm:id/send\"]')\n"
    "            if send_btn.exists:\n"
    "                send_btn.click()\n"
    "                logger.info(f'[PhysicalTool] 收款码已发送 price={price}')\n"
    "                return True\n"
    "            self._d.press('back')\n"
    "            return False\n"
    "        except Exception as e:\n"
    "            logger.error(f'[PhysicalTool] 收款码发送失败: {e}')\n"
    "            try:\n"
    "                self._d.press('back')\n"
    "            except Exception:\n"
    "                pass\n"
    "            return self.send_message(input_x, input_y, f'兄弟，请扫收款码，总计 {price:.0f} 元！')\n"
)

with open('physical_tool.py', 'a', encoding='utf-8') as f:
    f.write(part2)
print('part2 appended OK')
